#!/usr/bin/env node

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { parse as parseYaml } from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

// Default configuration values
const DEFAULTS = {
  site: {
    title: 'Whisper Transcript Reviewer',
    subtitle: 'Review VTTs Generated by Whisper or Whisper X.',
    footer_text: 'Whisper JSON Viewer',
    theme: 'synthwave'
  },
  build: {
    base_path: null // Will be auto-detected
  }
};

function loadConfig() {
  const configPath = path.join(rootDir, 'config.yml');

  console.log(`Looking for config at: ${configPath}`);
  console.log(`Config file exists: ${fs.existsSync(configPath)}`);

  let config = {
    site: { ...DEFAULTS.site },
    build: { ...DEFAULTS.build }
  };

  if (fs.existsSync(configPath)) {
    try {
      const yamlContent = fs.readFileSync(configPath, 'utf8');
      console.log(`Config file contents:\n${yamlContent}`);
      const parsed = parseYaml(yamlContent);

      // Deep merge with defaults
      if (parsed?.site) {
        config.site = { ...DEFAULTS.site, ...parsed.site };
      }
      if (parsed?.build) {
        config.build = { ...DEFAULTS.build, ...parsed.build };
      }
      console.log('Successfully loaded config.yml');
    } catch (error) {
      console.error('Error parsing config.yml:', error.message);
      console.log('Using default configuration');
    }
  } else {
    console.log('No config.yml found, using defaults');
  }

  return config;
}

function getBasePath(config) {
  // Priority: config file > GITHUB_REPOSITORY env var > default
  if (config.build.base_path) {
    return config.build.base_path;
  }

  const githubRepo = process.env.GITHUB_REPOSITORY;
  if (githubRepo) {
    const repoName = githubRepo.split('/')[1];
    return `/${repoName}/`;
  }

  return '/';
}

function updateIndexHtml(config) {
  const indexPath = path.join(rootDir, 'index.html');
  let html = fs.readFileSync(indexPath, 'utf8');

  // Update data-theme
  html = html.replace(
    /data-theme="[^"]*"/,
    `data-theme="${config.site.theme}"`
  );

  // Update <title>
  html = html.replace(
    /<title>[^<]*<\/title>/,
    `<title>${config.site.title}</title>`
  );

  // Update h1 heading
  html = html.replace(
    /(<h1 class="[^"]*">)[^<]*(<\/h1>)/,
    `$1${config.site.title}$2`
  );

  // Update subtitle paragraph
  html = html.replace(
    /(<p class="mb-5">)\s*[^<]*\s*(<\/p>)/,
    `$1\n          ${config.site.subtitle}\n        $2`
  );

  // Update footer text (first <p> in footer with font-semibold)
  html = html.replace(
    /(<footer[\s\S]*?<p class="font-semibold">)[^<]*(<\/p>)/,
    `$1${config.site.footer_text}$2`
  );

  fs.writeFileSync(indexPath, html);
  console.log('  Updated index.html');
}

function updateViteConfig(basePath) {
  const viteConfigPath = path.join(rootDir, 'vite.config.js');
  const viteConfig = `import { defineConfig } from 'vite'

export default defineConfig({
  base: '${basePath}',
})
`;
  fs.writeFileSync(viteConfigPath, viteConfig);
  console.log(`  Updated vite.config.js (base: '${basePath}')`);
}

function setupMediaConfig() {
  const configPath = path.join(rootDir, 'public', 'config.json');
  const defaultConfigPath = path.join(rootDir, 'public', 'config.default.json');

  // Check if config.json exists and has content
  let hasUserConfig = false;
  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf8').trim();
      const parsed = JSON.parse(content);
      hasUserConfig = Array.isArray(parsed) && parsed.length > 0;
    } catch {
      hasUserConfig = false;
    }
  }

  // If no user config, copy from default
  if (!hasUserConfig && fs.existsSync(defaultConfigPath)) {
    fs.copyFileSync(defaultConfigPath, configPath);
    console.log('  Copied config.default.json to config.json');
  } else if (hasUserConfig) {
    console.log('  Using existing config.json');
  } else {
    console.log('  Warning: No media configuration found');
  }
}

function main() {
  console.log('\n=== Build Configuration ===\n');

  const config = loadConfig();
  const basePath = getBasePath(config);

  console.log('Configuration:');
  console.log(`  Title: ${config.site.title}`);
  console.log(`  Subtitle: ${config.site.subtitle}`);
  console.log(`  Theme: ${config.site.theme}`);
  console.log(`  Footer: ${config.site.footer_text}`);
  console.log(`  Base Path: ${basePath}`);
  console.log('');

  console.log('Applying changes:');
  updateIndexHtml(config);
  updateViteConfig(basePath);
  setupMediaConfig();

  console.log('\n=== Configuration Complete ===\n');
}

main();
