#!/usr/bin/env node

import * as readline from 'readline';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

// Available DaisyUI themes
const THEMES = [
  'light', 'dark', 'cupcake', 'bumblebee', 'emerald', 'corporate',
  'synthwave', 'retro', 'cyberpunk', 'valentine', 'halloween', 'garden',
  'forest', 'aqua', 'lofi', 'pastel', 'fantasy', 'wireframe', 'black',
  'luxury', 'dracula', 'cmyk', 'autumn', 'business', 'acid', 'lemonade',
  'night', 'coffee', 'winter', 'dim', 'nord', 'sunset'
];

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt, defaultValue = '') {
  const displayPrompt = defaultValue ? `${prompt} [${defaultValue}]: ` : `${prompt}: `;
  return new Promise((resolve) => {
    rl.question(displayPrompt, (answer) => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

async function main() {
  console.log('\n========================================');
  console.log('  Whisper Transcript Reviewer Setup');
  console.log('========================================\n');
  console.log('This script will configure your new project.\n');

  // Gather configuration
  const config = {};

  config.projectTitle = await question('Project title (displayed in header)', 'Whisper Transcript Reviewer');
  config.projectSubtitle = await question('Project subtitle', 'Review VTTs Generated by Whisper or Whisper X.');

  const defaultSlug = slugify(config.projectTitle);
  config.repoName = await question('GitHub repository name (for deployment path)', defaultSlug);

  const defaultPackageName = slugify(config.projectTitle);
  config.packageName = await question('npm package name', defaultPackageName);
  config.packageDescription = await question('Package description', config.projectSubtitle);

  console.log(`\nAvailable themes: ${THEMES.slice(0, 10).join(', ')}...`);
  console.log(`(See all themes at https://daisyui.com/docs/themes/)`);
  config.theme = await question('DaisyUI theme', 'synthwave');

  if (!THEMES.includes(config.theme)) {
    console.log(`\nWarning: "${config.theme}" may not be a valid DaisyUI theme.`);
    const proceed = await question('Continue anyway? (y/n)', 'y');
    if (proceed.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      process.exit(0);
    }
  }

  config.footerText = await question('Footer text', config.projectTitle);

  console.log('\n--- Configuration Summary ---');
  console.log(`  Title: ${config.projectTitle}`);
  console.log(`  Subtitle: ${config.projectSubtitle}`);
  console.log(`  Repository: ${config.repoName}`);
  console.log(`  Package name: ${config.packageName}`);
  console.log(`  Theme: ${config.theme}`);
  console.log(`  Footer: ${config.footerText}`);
  console.log('-----------------------------\n');

  const confirm = await question('Apply these settings? (y/n)', 'y');
  if (confirm.toLowerCase() !== 'y') {
    console.log('Setup cancelled.');
    rl.close();
    process.exit(0);
  }

  // Apply configuration
  console.log('\nApplying configuration...\n');

  // 1. Update index.html
  const indexPath = path.join(rootDir, 'index.html');
  let indexHtml = fs.readFileSync(indexPath, 'utf8');

  // Update theme
  indexHtml = indexHtml.replace(
    /data-theme="[^"]*"/,
    `data-theme="${config.theme}"`
  );

  // Update title tag
  indexHtml = indexHtml.replace(
    /<title>[^<]*<\/title>/,
    `<title>${config.projectTitle}</title>`
  );

  // Update h1 heading
  indexHtml = indexHtml.replace(
    /(<h1 class="[^"]*">)[^<]*(<\/h1>)/,
    `$1${config.projectTitle}$2`
  );

  // Update subtitle paragraph
  indexHtml = indexHtml.replace(
    /(<p class="mb-5">\s*)[^<]*(\s*<\/p>)/,
    `$1${config.projectSubtitle}$2`
  );

  // Update footer text
  indexHtml = indexHtml.replace(
    /(<p class="font-semibold">)Whisper JSON Viewer(<\/p>)/,
    `$1${config.footerText}$2`
  );

  fs.writeFileSync(indexPath, indexHtml);
  console.log('  Updated index.html');

  // 2. Update vite.config.js
  const viteConfigPath = path.join(rootDir, 'vite.config.js');
  const viteConfig = `import { defineConfig } from 'vite'

export default defineConfig({
  base: '/${config.repoName}/',
})
`;
  fs.writeFileSync(viteConfigPath, viteConfig);
  console.log('  Updated vite.config.js');

  // 3. Update package.json
  const packagePath = path.join(rootDir, 'package.json');
  const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
  packageJson.name = config.packageName;
  packageJson.description = config.packageDescription;
  fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2) + '\n');
  console.log('  Updated package.json');

  // 4. Create empty config.json (preserve example)
  const configPath = path.join(rootDir, 'public', 'config.json');
  const exampleConfigPath = path.join(rootDir, 'public', 'config.example.json');

  // If config.example.json doesn't exist, create it from current config (first 2 entries as example)
  if (!fs.existsSync(exampleConfigPath)) {
    try {
      const currentConfig = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      const exampleEntries = currentConfig.slice(0, 2);
      fs.writeFileSync(exampleConfigPath, JSON.stringify(exampleEntries, null, 2) + '\n');
      console.log('  Created config.example.json');
    } catch (e) {
      // If current config is invalid or missing, create a template example
      const templateExample = [
        {
          "audio": "https://example.com/audio/sample.m3u8",
          "url": "https://example.com/transcripts/sample.json",
          "vtt": "https://example.com/vtts/sample.vtt",
          "name": "sample-transcript"
        }
      ];
      fs.writeFileSync(exampleConfigPath, JSON.stringify(templateExample, null, 2) + '\n');
      console.log('  Created config.example.json (template)');
    }
  }

  // Reset config.json to empty array
  fs.writeFileSync(configPath, '[]\n');
  console.log('  Reset config.json to empty array');

  // 5. Clear other config files if they exist
  const configToProcessPath = path.join(rootDir, 'public', 'config-to-process.json');
  const configRerunPath = path.join(rootDir, 'public', 'config-rerun.json');

  if (fs.existsSync(configToProcessPath)) {
    fs.writeFileSync(configToProcessPath, '[]\n');
    console.log('  Reset config-to-process.json');
  }

  if (fs.existsSync(configRerunPath)) {
    fs.writeFileSync(configRerunPath, '[]\n');
    console.log('  Reset config-rerun.json');
  }

  console.log('\n========================================');
  console.log('  Setup complete!');
  console.log('========================================\n');
  console.log('Next steps:');
  console.log('  1. Add your media files to public/config.json');
  console.log('     (See public/config.example.json for the format)');
  console.log('  2. Run "npm install" to install dependencies');
  console.log('  3. Run "npm run dev" to start development server');
  console.log('  4. Push to GitHub and enable GitHub Pages\n');

  rl.close();
}

main().catch((err) => {
  console.error('Setup failed:', err);
  rl.close();
  process.exit(1);
});
